FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    python3 python3-pip \
    unzip wget curl git \
    file binutils xxd \
    aapt apksigner zipalign \
    && rm -rf /var/lib/apt/lists/*

# jadx
RUN wget -q https://github.com/skylot/jadx/releases/download/v1.5.5/jadx-1.5.5.zip \
    -O /tmp/jadx.zip && unzip /tmp/jadx.zip -d /opt/jadx && \
    ln -s /opt/jadx/bin/jadx /usr/local/bin/jadx && \
    ln -s /opt/jadx/bin/jadx-gui /usr/local/bin/jadx-gui && \
    rm /tmp/jadx.zip

# apktool
RUN wget -q https://github.com/iBotPeaches/Apktool/releases/download/v3.0.1/apktool_3.0.1.jar \
    -O /usr/local/bin/apktool.jar && \
    wget -q https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool \
    -O /usr/local/bin/apktool && \
    chmod +x /usr/local/bin/apktool /usr/local/bin/apktool.jar

# semgrep
RUN pip3 install semgrep --quiet

# Python libs para PDF/reporting
RUN pip3 install reportlab fpdf2 jinja2 pandas tabulate --quiet

WORKDIR /analysis
